version: '3.8'

services:
  web:
    build: .
    command: gunicorn pathonout.asgi:application -k uvicorn.workers.UvicornWorker
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: mymap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
