databases:
  - name: mymapdb
    plan: free
    databaseName: mymap

services:
  - type: web
    plan: free
    name: pathonout
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mymapdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: GDAL_LIBRARY_PATH
        value: /usr/lib/libgdal.so.30
    dockerfile: Dockerfile  # Specify the Dockerfile to use for building the container

