# Generated by Django 5.0.6 on 2024-07-09 14:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=50)),
                ('sample_type', models.CharField(max_length=255)),
                ('acquisition_date', models.DateField()),
                ('sampling_date', models.DateField()),
                ('collection_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='labs.marker')),
            ],
        ),
    ]
