# Generated by Django 5.0.6 on 2024-07-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_isolate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isolate',
            name='supplier',
        ),
    ]
