# Generated by Django 5.0.6 on 2024-07-07 16:05

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_remove_isolate_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='isolate',
            name='collection_location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
