# Generated by Django 5.0.6 on 2024-07-07 16:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0004_isolate_collection_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="isolate",
            name="collection_location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
