# Generated by Django 5.0.6 on 2024-07-09 12:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_sample_delete_isolate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='collection_location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
